#!/bin/sh -xe

if [ -e "$HOME/..." ]; then
    echo "$HOME/... already exists"
    exit 1
fi

git submodule --recursive '
    [ -e .gitmodules ] && git submodule update --init || true'

# Without this, you get subdirs that you can't quickly hack on && commit
git submodule '
    git branch _dotdotdot_tmp_
    git checkout master
    git merge _dotdotdot_tmp_
'

ln -s "$PWD/..." "$HOME/..."

.../.bin/generate-...-conf

$HOME/.../bin/... install
