#!/bin/sh -xe

if [ -e "$HOME/..." ]; then
    echo "$HOME/... already exists"
    exit 1
fi

git submodule foreach --recursive \
    '[ -e .gitmodules ] && git submodule update --init || true'

# Without this, you get subdirs that you can't quickly hack on && commit
git submodule foreach 'git checkout master'

ln -s "$PWD/..." "$HOME/..."

.../.bin/generate-...-conf

$HOME/.../bin/... install
